apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
spec:
  template:
    spec:
      containers:
        # Change the value of image field below to your controller image URL
        - image: eu.gcr.io/gardener-project/gardener/etcd-druid:v0.13.0
          name: druid
