---

apiVersion: druid.gardener.cloud/v1alpha1
kind: Etcd
metadata:
  finalizers:
  - druid.gardener.cloud/etcd
  name: etcd
  namespace: garden
spec:
  selector:
    matchLabels:
      app: etcd
  annotations:
    app: etcd
    garden.sapcloud.io/role: controlplane
    networking.gardener.cloud/to-dns: allowed
    networking.gardener.cloud/to-private-networks: allowed
    networking.gardener.cloud/to-public-networks: allowed
    role: etcd-druid-leader-election-role
  backup:
    deltaSnapshotMemoryLimit: 1Gi
    deltaSnapshotPeriod: 300s
    fullSnapshotSchedule: 0 */24 * * *
    garbageCollectionPeriod: 43200s
    garbageCollectionPolicy: Exponential
    imageRepository: eu.gcr.io/gardener-project/gardener/etcdbrctl
    imageVersion: v0.12.0
    port: 8080
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 23m
        memory: 128Mi
    snapstoreTempDir: /var/etcd/data/temp
  etcd:
    Quota: 8Gi
    clientPort: 2379
    defragmentationSchedule: 0 */24 * * *
    enableTLS: false
    imageRepository: eu.gcr.io/gardener-project/gardener/etcd
    imageVersion: v3.4.13-bootstrap
    initialClusterState: new
    initialClusterToken: new
    metrics: basic
    pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 2500m
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 1000Mi
    serverPort: 2380
    storageCapacity: 80Gi
    storageClass: ""
  sharedConfig:
    autoCompactionMode: periodic
    autoCompactionRetention: 30m
  labels:
    app: etcd-statefulset
    garden.sapcloud.io/role: controlplane
    networking.gardener.cloud/to-dns: allowed
    networking.gardener.cloud/to-private-networks: allowed
    networking.gardener.cloud/to-public-networks: allowed
    role: etcd-druid-leader-election-role
  pvcRetentionPolicy: DeleteAll
  replicas: 1
  storageCapacity: 80Gi
  storageClass: gardener.cloud-fast
  store:
    storageContainer: test
    storageProvider: S3
    storePrefix: etcd-test
    storeSecret: etcd-backup
  tlsClientSecret: etcd-client-tls
  tlsServerSecret: etcd-server-tls
status:
  etcd:
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      labels:
        app: etcd
      name: etcd
      namespace: garden
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: etcd
      serviceName: etcd
      template:
        metadata:
          labels:
            app: etcd
        spec:
          containers:
          - command:
            - etcd
            - --name=etcd
            - --trusted-ca-file=/tls/ca.crt
            - --key-file=/tls/server.key
            - --cert-file=/tls/server.crt
            - --client-cert-auth
            - --listen-client-urls=https://0.0.0.0:2379
            - --advertise-client-urls=https://etcd-client.garden.svc:2379
            - --initial-cluster-state=new
            - --initial-cluster-token=new
            - --data-dir=/etcd-data
            image: quay.io/coreos/etcd:v3.5.1
            name: etcd
            ports:
            - containerPort: 2379
              name: client
            - containerPort: 2380
              name: discovery
            volumeMounts:
            - mountPath: /tls
              name: tls
            - mountPath: /etcd-data
              name: data
          volumes:
          - name: tls
            secret:
              secretName: etcd-tls
      volumeClaimTemplates:
      - metadata:
          labels:
            app: etcd
          name: data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 15Gi
