apiVersion: v1
data:
  ca.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvRENDQWVTZ0F3SUJBZ0lVZDNLSk
    tQR1RrR1JZdmFZQ2hxQzgyYjFmWXdnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZqRVVNQklH
    QTFVRUF4TUxaMkZ5WkdWdVpYSXRZMkV3SGhjTk1qRXhNakF6TURVMU1qQXdXaGNOTWpZeA
    pNakF5TURVMU1qQXdXakFXTVJRd0VnWURWUVFERXd0bllYSmtaVzVsY2kxallUQ0NBU0l3
    RFFZSktvWklodmNOCkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNRlFXNGUwZkxycWRldH
    hueHQ3WjVCWEl1OUFGWmlHKzZwQ2x6dkYKdTRMbWtSN1VXSkUwUjBnL1M3V282YzdvaC9I
    UlJTUU9xMkN2c3Y0WDNzYkJ5WnhVTnFpemVwM1FxdUQ0NS91ZQo5NExHcU5FbVBBbGcvbj
    d1a3JQZkw0TjBNZThFTEcrd2VkL1FXb0ZiVldXM3NMUzRyYlN3Tm0xUmJBWXJGQktDCmFM
    VmFxc2d1SEExcUtvNXRXV21NVkw1REdIbS9iMmk2VFBoaWJWUVJoNEJqcEUwNUFpeUxRcX
    d6RzhKMkp4UkQKSkNTdkdTSWFnTkt5TjFOK0RSaVMyWkxsNU9BQUlhaDBUem1kYjZ4anl2
    NkhMZGJ0cjBsL0pOU256ZWpmbWFURgp5anFwSS9iblBKWWJhckNZNHFCZXNMWWxLZmMyTn
    ovWHhXVFdLY3IrWjl6bnQvY0NBd0VBQWFOQ01FQXdEZ1lEClZSMFBBUUgvQkFRREFnRUdN
    QThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGUHMyU2M4cE9tQmEKZzZmaF
    FpcnlvczlCWUpucU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQmhGcitkemo4ckhlOEhH
    aUh5QllQbAp0SHBGNTFSbmQ2bzE0dVFzRW9MdGNPUFRsazgyazZyVGU4RXlId2txNUlSVV
    ZQVTFtREJUVy9KcTg2V3VMNTQ0ClJNYjVvTStiOFJsbGdnVHdBZjNOSDBDeFYwNkhHU0lk
    bjBHbHR6YzZnMXNYVTM1UWt5czh0eGkyeElKcmplaDEKcEZUR1N6bVZPd3AxSkpDOHJmM2
    Z5ck8wdktncEJUQ0hWQVQ0QmprQS8zZjJmY2JQc3g1ODA0V3ozQXFaNjdSQgpSbnNqV2Ra
    cmw5OWJqQ3FUU1pYZ3RZeVVmZlh5OGhraENabWFPd2pKU3lZV2pzcENHbDZNeGgyTG14MU
    d0L24rCnNvelhsQ2xVWnU5UEpvMlpEOWdsaHdpTTlTWGJaUTFtL0graEZ0bitkWmRKZ21z
    MnhpZ055dzdrWDNNbUtnS0oKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  server.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVzakNDQTVxZ0F3SUJBZ0lVZWg2bW
    1Rbm1aNjlRQW53aUNxMDZOL2EyM2gwd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZqRVVNQklH
    QTFVRUF4TUxaMkZ5WkdWdVpYSXRZMkV3SGhjTk1qRXhNakF6TURZeU1UQXdXaGNOTXpFeA
    pNREV5TURZeU1UQXdXakFQTVEwd0N3WURWUVFERXdSbGRHTmtNSUlCSWpBTkJna3Foa2lH
    OXcwQkFRRUZBQU9DCkFROEFNSUlCQ2dLQ0FRRUF4ZVM1TFNjM3k4N2F3R2VQQUFrVHpQb3
    Y2NmZEMC9INTVta29XZGliclV6dzRhbysKcGZIbkNiK0QweDFGbnlGZCtVV1hLSGlvSGN1
    QXhHaWZvUlZjWHNZalJlditpbEUvNnE4UU5QSE5ady9XOURkcgpoejlvZmxaM3NNU0krVG
    xDaEs5U1ZNaVRZTGw4RjNlYTBpVERBMko3aGgzMFJDQ3VxSFc3MEZlMU9vQ3UrTXhiCkFm
    R2tzQ2l6QXN4WmdRa0hYWVF0bGJZbEpPVE5nMk54L081R2Y1YUoxR2M1SkEwOFZpS3BBek
    5xTUF4eTdTd0gKVjZlWU01K0pnTWxYVUtpRHZtU01qMjlpUmF3cGp2YzU3V1NKZldNbHRh
    clJ5OWhWa1JSSGwrdTIrWmhtYUpxUQpMTFVpTkQzd2MvcTdxM21MaHNLRlNQYkdJZkdYNE
    dTWGJVVkhId0lEQVFBQm80SUIvVENDQWZrd0RnWURWUjBQCkFRSC9CQVFEQWdXZ01CMEdB
    MVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFNQmdOVkhSTUIKQWY4RU
    FqQUFNQjBHQTFVZERnUVdCQlJiTVc1WUZxZi9yYmJkSGRObzN1dG93OENESHpBZkJnTlZI
    U01FR0RBVwpnQlQ3TmtuUEtUcGdXb09uNFVJcThxTFBRV0NaNmpDQ0FYZ0dBMVVkRVFTQ0
    FXOHdnZ0ZyZ2dsc2IyTmhiR2h2CmMzU0NCR1YwWTJTQ0MyVjBZMlF1WjJGeVpHVnVnZzls
    ZEdOa0xtZGhjbVJsYmk1emRtT0NGMlYwWTJRdVoyRnkKWkdWdUxuTjJZeTVqYkhWemRHVn
    lnaDFsZEdOa0xtZGhjbVJsYmk1emRtTXVZMngxYzNSbGNpNXNiMk5oYklJTApaWFJqWkMx
    amJHbGxiblNDRW1WMFkyUXRZMnhwWlc1MExtZGhjbVJsYm9JV1pYUmpaQzFqYkdsbGJuUX
    VaMkZ5ClpHVnVMbk4yWTRJZVpYUmpaQzFqYkdsbGJuUXVaMkZ5WkdWdUxuTjJZeTVqYkhW
    emRHVnlnaVJsZEdOa0xXTnMKYVdWdWRDNW5ZWEprWlc0dWMzWmpMbU5zZFhOMFpYSXViRz
    lqWVd5Q0MyVjBZMlF0TUM1bGRHTmtnaEpsZEdOawpMVEF1WlhSalpDNW5ZWEprWlc2Q0Zt
    VjBZMlF0TUM1bGRHTmtMbWRoY21SbGJpNXpkbU9DSG1WMFkyUXRNQzVsCmRHTmtMbWRoY2
    1SbGJpNXpkbU11WTJ4MWMzUmxjb0lrWlhSalpDMHdMbVYwWTJRdVoyRnlaR1Z1TG5OMll5
    NWoKYkhWemRHVnlMbXh2WTJGc2h3Ui9BQUFCTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQV
    FCM3NYakR3cFFxeHNCcQppaUhRbmJkWlZrQW1uOE5zaXJGR21HRERCbUVNRTVacFBJV3BP
    eERaYk9mdDZ2TjhWVHpQaURzcGZJYzVxNEs4Ci9Mb0RjaUNlWVFTbVZ3Z1B3ZkxpaWVRUj
    dXbW16WWlueStsUEtKdXUzQkVHejhzUHIvM3pNM2xBekJvNlYrUXIKNDgvVHdnM2I4NmFl
    bmducGx4VFIrUmVrc3ljeFVwcjhmT2doa1FNSmhEOUlReDlEQ0ZpcURuTTFwQVhPY0VWNQ
    paZVo1bnpXUHRTRlZINTdFWFZmNUF4d2x5KzdVbG5JTmw4SFp0aU0xUDhPc1ZuZzFMMk91
    cW5tK2c5ZTdHa1p3ClRoaTNBdEhFTFgyY0MrRGtEVGJQeWpsWTZabmszZEdCcWhOWUlwOU
    FQd2RPUGQ0Q2lYS3h6d2h6TzhQS1FYTncKdXA4SGZzNi8KLS0tLS1FTkQgQ0VSVElGSUNB
    VEUtLS0tLQo=
  server.key: |
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBeGVTNU
    xTYzN5ODdhd0dlUEFBa1R6UG92NjZmRDAvSDU1bWtvV2RpYnJVenc0YW8rCnBmSG5DYitE
    MHgxRm55RmQrVVdYS0hpb0hjdUF4R2lmb1JWY1hzWWpSZXYraWxFLzZxOFFOUEhOWncvVz
    lEZHIKaHo5b2ZsWjNzTVNJK1RsQ2hLOVNWTWlUWUxsOEYzZWEwaVREQTJKN2hoMzBSQ0N1
    cUhXNzBGZTFPb0N1K014YgpBZkdrc0NpekFzeFpnUWtIWFlRdGxiWWxKT1ROZzJOeC9PNU
    dmNWFKMUdjNUpBMDhWaUtwQXpOcU1BeHk3U3dIClY2ZVlNNStKZ01sWFVLaUR2bVNNajI5
    aVJhd3BqdmM1N1dTSmZXTWx0YXJSeTloVmtSUkhsK3UyK1pobWFKcVEKTExVaU5EM3djL3
    E3cTNtTGhzS0ZTUGJHSWZHWDRHU1hiVVZISHdJREFRQUJBb0lCQVFDZ21JS1NteTRUcnRZ
    bApxS1VMTVZLcFdTd0VnVXhSdHlESGxQVlRISThSNzh2WVJ2RzZkL3E0Rlh6a21lL0RPUy
    9yT0VkNFo1cC9PNFJQCllGeVRQQ09QSWhyRUJzVzErRVAzcjRSbWd3amZKNktZNUZUV0dH
    WXppUFp2TkwrNENYanE5dURJdjFHakFFUXQKUXpvWWFnNzhzekp0WCtlNFZoR0gwcXZOWX
    pCR3ZYUTV3Q1J1OTY0MHhQeFJtcGhmN3hUOVptTWp1bHp4R3dpcgprVVYyZ1F6b3krK3hz
    SGxKMmNXdlZGOC82cDRGaHJjaVVLTGt5QWZpK2FsSTlsOUhJY3Z3djRhblQ4UnVPWkpGCj
    dUOURIV1E2bVRNU1NTc3kvKzhzb1MwbHM4TjF2bGZQQ09aMkxjMnZ4ZTJoVURPNjFIbVhj
    NDdrRGRNVkR2T3cKL0RCcVVEbXBBb0dCQU5tVmF0UHZlTGUzaElNUU5Pb1hpS3oxWEZEZ2
    o0TGpERHptbzd4a282MFFLd2xBdDFSYwoyaU1qYnRsbFR6cWoyNUhPU0ZhdHhTSkpReFpE
    bng2QWloNkgrNUlhQndvRWhiS3g2RzNVY1k5RVI2WHJJTVh5Ck9OdU9EcXltdzRNSWtWMz
    NEZzE5WTlmSU1mczRoak5OOFZ6TnBmZXQ4VW5TT1FKTzJmU1hDaEFWQW9HQkFPalYKVTVa
    UXpPVDFxVFBSenRlYTNyNTVrRnp0RTBMeks5ZW1jcmdWb1NsTWFiUlorNzk1Q2g2V3E5Mj
    ZiUDM3eFhYdApKMTdBajVOZmxXOUJXRGV0N0kvZ016YzRBc1RpRDlDZkEvc000UHFBbHNi
    RVhNMk1zeGNmYy9CVHlLV1JscTBlCkNicDJSSnVyVklYS29wRlZJYkdmbm41ak1uZE9XVn
    QrekgyczBaTmpBb0dCQUpHcGgrVHVNbUM3aVFpODlzK28KaGFWVWRVTG5zdXVxMkd5RTh5
    U1NNMGtPdytEajVGZWorWjBBZ1pza1NaQTJWaTRjYlMwcUZBbEtCcEdISDZVcAo1RTFnTj
    dpdGwvekszajZzLzY5WFE5Ym5uUmVrZTBKSlVHc2JoUk5zYVFMMTMydUtrMnZRZitEYmN5
    cDl3c25oCjZpMTR0eDFDNDMvS0xzUXV5WmNHN29PcEFvR0FTd1RSRmRHYTh2cWtOZW9YOX
    lnVE5OUCtTN0tuVGg4RHRVd1EKRW5nRm9VVFptaDZVR3JGcExVbm12bDVlMThiVGJKZW80
    OEt2Z0JDQUdZUzRZOWhLTEdGVW55b1EybGJzT1kvQwp2SlQ5dURqT1crVFE4Zm12aW5lNz
    UyZFhjdUZoNXcyU25OMldaWUhpamVrb1VDTlo0OTFHTi9yR08rS21yL0ErCit3OC94M2tD
    Z1lFQXQ4aU9XVXBMVXNXQkg1L21ENWF5MWhoaTlNc1psSm50NnY4bUd5UXU1MDBlekE3NW
    lGYXYKMS8xbWlkVzBKU2R6TDYxUW4wbC9Ia09EYytOK1hDSVRraEsxRTlXTktHTTM5ZXNU
    TmxJc1Z1bkVrWTdPalZhOAp3ekcwSE1iMUNTZFo3WUxtbVQ4UHNaN0cwZEdzWHh5clc1Qk
    1HTEZ6WlVuQ1FveHpzQi82ZVlrPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  labels:
    app: etcd
  name: etcd-tls
  namespace: garden
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd
  name: etcd
  namespace: garden
spec:
  clusterIP: None
  ports:
  - name: client
    port: 2379
    targetPort: 2379
  - name: discovery
    port: 2380
    targetPort: 2380
  publishNotReadyAddresses: true
  selector:
    app: etcd
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd
  name: etcd-client
  namespace: garden
spec:
  ports:
  - name: client
    port: 2379
    targetPort: 2379
  selector:
    app: etcd
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: etcd
  name: etcd
  namespace: garden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  serviceName: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - command:
        - etcd
        - --name=etcd
        - --trusted-ca-file=/tls/ca.crt
        - --key-file=/tls/server.key
        - --cert-file=/tls/server.crt
        - --client-cert-auth
        - --listen-client-urls=https://0.0.0.0:2379
        - --advertise-client-urls=https://etcd-client.garden.svc:2379
        - --initial-cluster-state=new
        - --initial-cluster-token=new
        - --data-dir=/etcd-data
        image: quay.io/coreos/etcd:v3.5.1
        name: etcd
        ports:
        - containerPort: 2379
          name: client
        - containerPort: 2380
          name: discovery
        volumeMounts:
        - mountPath: /tls
          name: tls
        - mountPath: /etcd-data
          name: data
      volumes:
      - name: tls
        secret:
          secretName: etcd-tls
  volumeClaimTemplates:
  - metadata:
      labels:
        app: etcd
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: "default"
      resources:
        requests:
          storage: 15Gi
