//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"git.viettel.vn/cloud-native-cicd/kubernetes-engine/cluster-api-provider-viettel/viettel-cloud/api"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/cluster-api/errors"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViettelCluster) DeepCopyInto(out *ViettelCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViettelCluster.
func (in *ViettelCluster) DeepCopy() *ViettelCluster {
	if in == nil {
		return nil
	}
	out := new(ViettelCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ViettelCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViettelClusterList) DeepCopyInto(out *ViettelClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ViettelCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViettelClusterList.
func (in *ViettelClusterList) DeepCopy() *ViettelClusterList {
	if in == nil {
		return nil
	}
	out := new(ViettelClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ViettelClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViettelClusterSpec) DeepCopyInto(out *ViettelClusterSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViettelClusterSpec.
func (in *ViettelClusterSpec) DeepCopy() *ViettelClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ViettelClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViettelClusterStatus) DeepCopyInto(out *ViettelClusterStatus) {
	*out = *in
	if in.Vpc != nil {
		in, out := &in.Vpc, &out.Vpc
		*out = new(api.VPC)
		(*in).DeepCopyInto(*out)
	}
	if in.Subnet != nil {
		in, out := &in.Subnet, &out.Subnet
		*out = new(api.Subnet)
		(*in).DeepCopyInto(*out)
	}
	if in.LoadBalancer != nil {
		in, out := &in.LoadBalancer, &out.LoadBalancer
		*out = new(api.LoadBalancerDetail)
		(*in).DeepCopyInto(*out)
	}
	if in.ServerGroup != nil {
		in, out := &in.ServerGroup, &out.ServerGroup
		*out = new(api.ServerGroupDetail)
		(*in).DeepCopyInto(*out)
	}
	if in.Listener != nil {
		in, out := &in.Listener, &out.Listener
		*out = new(api.ListenerDetail)
		(*in).DeepCopyInto(*out)
	}
	if in.SecurityGroup != nil {
		in, out := &in.SecurityGroup, &out.SecurityGroup
		*out = new(api.SecurityGroup)
		(*in).DeepCopyInto(*out)
	}
	if in.FailureReason != nil {
		in, out := &in.FailureReason, &out.FailureReason
		*out = new(errors.ClusterStatusError)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViettelClusterStatus.
func (in *ViettelClusterStatus) DeepCopy() *ViettelClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ViettelClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViettelClusterTemplate) DeepCopyInto(out *ViettelClusterTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViettelClusterTemplate.
func (in *ViettelClusterTemplate) DeepCopy() *ViettelClusterTemplate {
	if in == nil {
		return nil
	}
	out := new(ViettelClusterTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ViettelClusterTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViettelClusterTemplateList) DeepCopyInto(out *ViettelClusterTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ViettelClusterTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViettelClusterTemplateList.
func (in *ViettelClusterTemplateList) DeepCopy() *ViettelClusterTemplateList {
	if in == nil {
		return nil
	}
	out := new(ViettelClusterTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ViettelClusterTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViettelClusterTemplateSpec) DeepCopyInto(out *ViettelClusterTemplateSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViettelClusterTemplateSpec.
func (in *ViettelClusterTemplateSpec) DeepCopy() *ViettelClusterTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(ViettelClusterTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViettelClusterTemplateStatus) DeepCopyInto(out *ViettelClusterTemplateStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViettelClusterTemplateStatus.
func (in *ViettelClusterTemplateStatus) DeepCopy() *ViettelClusterTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(ViettelClusterTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViettelMachine) DeepCopyInto(out *ViettelMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViettelMachine.
func (in *ViettelMachine) DeepCopy() *ViettelMachine {
	if in == nil {
		return nil
	}
	out := new(ViettelMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ViettelMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViettelMachineList) DeepCopyInto(out *ViettelMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ViettelMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViettelMachineList.
func (in *ViettelMachineList) DeepCopy() *ViettelMachineList {
	if in == nil {
		return nil
	}
	out := new(ViettelMachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ViettelMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViettelMachineSpec) DeepCopyInto(out *ViettelMachineSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViettelMachineSpec.
func (in *ViettelMachineSpec) DeepCopy() *ViettelMachineSpec {
	if in == nil {
		return nil
	}
	out := new(ViettelMachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViettelMachineStatus) DeepCopyInto(out *ViettelMachineStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViettelMachineStatus.
func (in *ViettelMachineStatus) DeepCopy() *ViettelMachineStatus {
	if in == nil {
		return nil
	}
	out := new(ViettelMachineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViettelMachineTemplate) DeepCopyInto(out *ViettelMachineTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViettelMachineTemplate.
func (in *ViettelMachineTemplate) DeepCopy() *ViettelMachineTemplate {
	if in == nil {
		return nil
	}
	out := new(ViettelMachineTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ViettelMachineTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViettelMachineTemplateList) DeepCopyInto(out *ViettelMachineTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ViettelMachineTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViettelMachineTemplateList.
func (in *ViettelMachineTemplateList) DeepCopy() *ViettelMachineTemplateList {
	if in == nil {
		return nil
	}
	out := new(ViettelMachineTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ViettelMachineTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViettelMachineTemplateSpec) DeepCopyInto(out *ViettelMachineTemplateSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViettelMachineTemplateSpec.
func (in *ViettelMachineTemplateSpec) DeepCopy() *ViettelMachineTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(ViettelMachineTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViettelMachineTemplateStatus) DeepCopyInto(out *ViettelMachineTemplateStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViettelMachineTemplateStatus.
func (in *ViettelMachineTemplateStatus) DeepCopy() *ViettelMachineTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(ViettelMachineTemplateStatus)
	in.DeepCopyInto(out)
	return out
}
