# permissions for end users to view viettelmachinetemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: viettelmachinetemplate-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-api-provider-viettel
    app.kubernetes.io/part-of: cluster-api-provider-viettel
    app.kubernetes.io/managed-by: kustomize
  name: viettelmachinetemplate-viewer-role
rules:
- apiGroups:
  - infrastructure.sigs.k8s.io
  resources:
  - viettelmachinetemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.sigs.k8s.io
  resources:
  - viettelmachinetemplates/status
  verbs:
  - get
